name: Build and publish go package
description: Build and publish go package to a private source.ag github repository

inputs:
  version-context:
    description: 'Version context to use'
    required: false

runs:
  using: composite
  steps:
    - uses: actions/checkout@v2
    - name: Greet Go
      shell: bash
      run: echo Hello Go/${{ inputs.version-context }}